import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/ui/header-2";
import { StickyFooter } from "@/components/ui/sticky-footer";
import LenisProvider from "@/components/LenisProvider";
import AOSInit from "@/components/AOSInit";
import { WhatsAppButton } from "@/components/WhatsAppButton";
import TrackingScript from "@/components/TrackingScript";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${workSans.variable} antialiased overscroll-none`}>
        <LenisProvider>
          <AOSInit />
          <TrackingScript />
          <Header />
          {children}
          <StickyFooter />
          <WhatsAppButton />
        </LenisProvider>
      </body>
    </html>
  );
}
