import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/ui/header-2";
import { StickyFooter } from "@/components/ui/sticky-footer";
import LenisProvider from "@/components/LenisProvider";
import AOSInit from "@/components/AOSInit";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased overscroll-none`}>
        <LenisProvider>
          <AOSInit />
          <Header />
          {children}
          <StickyFooter />
        </LenisProvider>
      </body>
    </html>
  );
}
